name: DiscoveryServer CI/CD

on:
  push:
    branches: Production
    paths:
      - "DiscoveryServer/**"
      - ".github/workflows/DiscoveryServer.yml"
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run subtree-split
      id: split
      run: echo "::set-output name=data::$(git subtree split --prefix=DiscoveryServer Production)"
    - name: print output
      run: echo ${{ steps.split.outputs.data }}
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Heroku login credentials
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
      - name: Add backend remote origin
        run: heroku git:remote -a ${{ secrets.HEROKU_DISCOVERY_APP_NAME }}
      - name: Deploy backend to Heroku
        run: git push heroku `git subtree split --prefix=DiscoveryServer Production`:refs/heads/master --force
