name: DynamicRoutingServer CI/CD

on:
  pull_request:
    branches: Production
    paths:
      - "DynamicRoutingServer/**"
      - ".github/workflows/DynamicRoutingServer_pull.yml"
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' 
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
      working-directory: DynamicRoutingServer
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  deploy:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Heroku login credentials
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
      - name: Add backend remote origin
        run: heroku git:remote -a ${{ secrets.HEROKU_DYNAMIC_APP_NAME }}
      - name: Deploy backend to Heroku
        run: git push heroku `git subtree split --prefix=DynamicRoutingServer --branch=Develop_DynamicRoutingServer`:refs/heads/master --force
